using System.Diagnostics.CodeAnalysis;
using Content.Client.Guidebook.Controls;
using Content.Client.Guidebook.Richtext;
using Content.Client.UserInterface.ControlExtensions;
using Content.Shared.Chemistry.Reaction;
using Content.Shared.Chemistry.Reagent;
using Content.Shared.EntityEffects.Effects.EntitySpawning;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Trieste;

/// <summary>
/// Control for embedding a chemical reaction into a guidebook. This is used for Food recipes.
/// </summary>
[UsedImplicitly, GenerateTypedNameReferences]
public sealed partial class GuideReactionEmbed : PanelContainer, IDocumentTag, ISearchableControl
{
    [Dependency] private IPrototypeManager _protoMan = default!;
    [Dependency] private ILogManager _logManager = default!;

    private readonly ISawmill _sawmill;

    public GuideReactionEmbed()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        MouseFilter = MouseFilterMode.Stop;
        _sawmill = _logManager.GetSawmill("Trieste|GuideReactionEmbed");
    }

    public GuideReactionEmbed(ProtoId<ReactionPrototype> reactionProto) : this()
    {
        if (_protoMan.TryIndex(reactionProto, out var reaction))
        {
            GenerateControl(reaction);
        }
        else
        {
            _sawmill.Error($"Missing the reaction prototype: {reactionProto}");
        }
    }

    public bool CheckMatchesSearch(string query)
    {
        return this.ChildrenContainText(query);
    }

    public void SetHiddenState(bool state, string query)
    {
        Visible = CheckMatchesSearch(query) ? state : !state;
    }

    public bool TryParseTag(Dictionary<string, string> args, [NotNullWhen(true)] out Control? control)
    {
        control = null;
        if (!args.TryGetValue("Reaction", out var id))
        {
            _sawmill.Error("Reaction embed tag is missing reaction prototype argument");
            return false;
        }

        if (!_protoMan.TryIndex<ReactionPrototype>(id, out var reaction))
        {
            _sawmill.Error($"Specified reaction prototype \"{id}\" is not a valid reaction prototype");
            return false;
        }

        GenerateControl(reaction);

        control = this;
        return true;
    }

    private void GenerateControl(ReactionPrototype reaction)
    {
        // Look for a resulting entity to promote to the header.
        EntityPrototype? headerEntity = null;
        string? headerEntityId = null;

        foreach (var effect in reaction.Effects)
        {
            if (effect is SpawnEntity spawnEffect &&
                _protoMan.TryIndex<EntityPrototype>(spawnEffect.Entity, out var entity))
            {
                headerEntity = entity;
                headerEntityId = spawnEffect.Entity;
                break;
            }
        }

        // Header: use the resulting entity's name if there is one - otherwise we fall back to the reaction name.
        var msg = new FormattedMessage();
        msg.AddMarkupOrThrow(Loc.GetString("guidebook-reaction-name",
            ("name", headerEntity?.Name ?? reaction.Name)));
        ResultName.SetMessage(msg);

        if (headerEntityId != null)
        {
            HeaderIconContainer.AddChild(new GuideEntityEmbed(headerEntityId, false, false));
        }

        // The reagents in the reaction.
        foreach (var (reagentId, reactant) in reaction.Reactants)
        {
            if (!_protoMan.TryIndex<ReagentPrototype>(reagentId, out var reagent))
                continue;

            var colorMsg = new FormattedMessage();
            colorMsg.AddMarkupOrThrow(Loc.GetString("guidebook-microwave-reagent-color-display",
                ("color", reagent.SubstanceColor)));

            var colorLabel = new RichTextLabel();
            colorLabel.SetMessage(colorMsg);
            ReactantsGrid.AddChild(colorLabel);

            var nameMsg = new FormattedMessage();
            nameMsg.AddMarkupOrThrow(Loc.GetString("guidebook-reaction-reactant-display",
                ("reagent", reagent.LocalizedName),
                ("amount", reactant.Amount)));
            var nameLabel = new RichTextLabel();
            nameLabel.SetMessage(nameMsg);
            ReactantsGrid.AddChild(nameLabel);
        }
    }
}
