- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Bagel
  - Box
  - Elkridge
  - Fland
  - Marathon
  - Oasis
  - Packed
  - Plasma
  - Reach
  - Exo
  - Snowball
  - Saltern
  - Meta # Claw Command
  - Edge # Claw Command
  - Shoukou # Claw Command
  - Pebble # Claw Command
  - Asterisk # Claw Command - snow planet
  - Glacier # Claw Command - ported from space/
  #- Relic
