using System;
using Content.Shared._ClawCommand.Voidfox;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._ClawCommand.Voidfox;

[GenerateTypedNameReferences]
public sealed partial class VoidfoxWindow : DefaultWindow
{
    public event Action? OnToggleLadder;
    public event Action? OnToggleCockpit;
    public event Action? OnToggleFuelLatch;

    public VoidfoxWindow()
    {
        RobustXamlLoader.Load(this);

        LadderButton.OnPressed += _ => OnToggleLadder?.Invoke();
        CockpitButton.OnPressed += _ => OnToggleCockpit?.Invoke();
        FuelLatchButton.OnPressed += _ => OnToggleFuelLatch?.Invoke();
    }

    public void UpdateState(VoidfoxBuiState state)
    {
        LadderStateLabel.Text = state.LadderDeployed
            ? Loc.GetString("voidfox-state-deployed")
            : Loc.GetString("voidfox-state-retracted");
        LadderButton.Text = state.LadderDeployed
            ? Loc.GetString("voidfox-button-retract")
            : Loc.GetString("voidfox-button-deploy");

        CockpitStateLabel.Text = state.CockpitLatchOpen
            ? Loc.GetString("voidfox-state-open")
            : Loc.GetString("voidfox-state-closed");
        CockpitButton.Text = state.CockpitLatchOpen
            ? Loc.GetString("voidfox-button-close")
            : Loc.GetString("voidfox-button-open");

        FuelLatchStateLabel.Text = state.FuelLatchOpen
            ? Loc.GetString("voidfox-state-open")
            : Loc.GetString("voidfox-state-closed");
        FuelLatchButton.Text = state.FuelLatchOpen
            ? Loc.GetString("voidfox-button-close")
            : Loc.GetString("voidfox-button-open");

        OccupantLabel.Text = state.HasOccupant
            ? Loc.GetString("voidfox-occupant-present")
            : Loc.GetString("voidfox-occupant-empty");

        PressureLabel.Text = Loc.GetString("voidfox-format-pressure", ("kpa", state.Pressure.ToString("F1")));
        TemperatureLabel.Text = Loc.GetString("voidfox-format-temperature", ("k", state.Temperature.ToString("F1")));
        VolumeLabel.Text = Loc.GetString("voidfox-format-volume", ("l", state.Volume.ToString("F0")));
        MolesLabel.Text = Loc.GetString("voidfox-format-moles", ("mol", state.FuelTotalMoles.ToString("F2")));
        PurityLabel.Text = Loc.GetString("voidfox-format-percent", ("pct", (state.PlasmaFraction * 100f).ToString("F1")));

        var canIgnite = state.PlasmaFraction >= state.MinPlasmaPurity && state.FuelTotalMoles > 0f;
        IgnitionLabel.Text = canIgnite
            ? Loc.GetString("voidfox-ignition-ready")
            : Loc.GetString("voidfox-ignition-blocked", ("min", (state.MinPlasmaPurity * 100f).ToString("F0")));
    }
}
